### ISSUE TITLE
Change color and icon for "pending" step in order status

### ISSUE THREAD

**Issue by pglevy** [sarnikbixal/cms_prototype#4]
Let's use "fa-square" for icon and "text-secondary" for color. Not sure where to change these in the code. The other icons/colors on this page are fine.

![image](https://user-images.githubusercontent.com/5177337/59554358-bb6aef00-8f6f-11e9-9020-851c6b7dfd61.png)

**Comment by sarnikbixal** [comment]
now that we have the -o should the pending be square-o?

**Comment by pglevy** [comment]
Yes
